"""
Grid-searches hysteresis thresholds AND median-filter size for
NOVA-VAD-frame-v2 on the VAL split ONLY (data/scenes/val/ — generated by
scripts/generate_val_split.py from train-source files, never overlapping
data/scenes/test/). Same selection objective as v1's tuning (frame F1) for
a fair, non-cherry-picked comparison — not switched to a different metric
post-hoc.

Run: python3 -m scripts.tune_frame_vad_v2
"""
import glob
import json
import os

import joblib

from scripts.frame_vad_v2 import predict_hop_probs_v2, _apply_median_filter
from scripts.frame_vad_v1 import apply_hysteresis

VAL_DIR = "data/scenes/val"
OUT_PATH = "models/frame_vad_v2_hysteresis.json"

T_ON_GRID = [0.35, 0.45, 0.55, 0.65, 0.75]
T_OFF_GRID = [0.15, 0.25, 0.35, 0.45]
MEDIAN_FILTER_GRID = [1, 3, 5]  # in hops (1 = off, 3 = 300ms, 5 = 500ms)
MIN_SPEECH_FRAMES = 15
MIN_GAP_FRAMES = 15


def frame_f1_precision_recall(pred, truth):
    n = min(len(pred), len(truth))
    pred, truth = pred[:n], truth[:n]
    tp = sum(1 for p, t in zip(pred, truth) if p == 1 and t == 1)
    fp = sum(1 for p, t in zip(pred, truth) if p == 1 and t == 0)
    fn = sum(1 for p, t in zip(pred, truth) if p == 0 and t == 1)
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    return f1, precision, recall


def tune():
    rf = joblib.load("models/frame_vad_v2_rf.pkl")
    gbt = joblib.load("models/frame_vad_v2_gbt.pkl")
    scaler = joblib.load("models/frame_vad_v2_scaler.pkl")

    val_scenes = []
    for json_path in sorted(glob.glob(os.path.join(VAL_DIR, "*.json"))):
        with open(json_path) as f:
            meta = json.load(f)
        wav_path = json_path.replace(".json", ".wav")
        print(f"  Computing hop probabilities for {meta['scene_id']}...")
        hop_probs = predict_hop_probs_v2(wav_path, rf, gbt, scaler, meta["duration_ms"])
        val_scenes.append((hop_probs, meta["frame_labels_10ms"]))

    total_combos = len(T_ON_GRID) * len(T_OFF_GRID) * len(MEDIAN_FILTER_GRID)
    print(f"\nGrid-searching {total_combos} (T_on, T_off, median_filter_size) combinations "
          f"on {len(val_scenes)} val scenes (selection objective: frame F1)...")

    best = {"f1": -1}
    for mf_size in MEDIAN_FILTER_GRID:
        filtered_scenes = [
            (_apply_median_filter(hop_probs, mf_size), truth) for hop_probs, truth in val_scenes
        ]
        for t_on in T_ON_GRID:
            for t_off in T_OFF_GRID:
                if t_off >= t_on:
                    continue
                all_pred, all_truth = [], []
                for hop_probs, truth in filtered_scenes:
                    mask = apply_hysteresis(hop_probs, t_on, t_off, MIN_SPEECH_FRAMES, MIN_GAP_FRAMES)
                    n = min(len(mask), len(truth))
                    all_pred.extend(mask[:n])
                    all_truth.extend(truth[:n])

                f1, precision, recall = frame_f1_precision_recall(all_pred, all_truth)
                print(f"    mf={mf_size}, T_on={t_on}, T_off={t_off}: "
                      f"val F1={f1*100:.2f}% (P={precision*100:.1f}%, R={recall*100:.1f}%)")
                if f1 > best["f1"]:
                    best = {"f1": f1, "precision": precision, "recall": recall,
                             "t_on": t_on, "t_off": t_off, "median_filter_size": mf_size}

    params = {
        "t_on": best["t_on"],
        "t_off": best["t_off"],
        "min_speech_frames": MIN_SPEECH_FRAMES,
        "min_gap_frames": MIN_GAP_FRAMES,
        "median_filter_size": best["median_filter_size"],
        "tuned_on": "data/scenes/val (40 scenes, train-source files, seed=43)",
        "selection_objective": "frame F1 (same objective as v1 tuning, for comparability)",
        "val_f1_pct": round(best["f1"] * 100, 2),
        "val_precision_pct": round(best["precision"] * 100, 2),
        "val_recall_pct": round(best["recall"] * 100, 2),
    }
    with open(OUT_PATH, "w") as f:
        json.dump(params, f, indent=2)

    print(f"\nBest: T_on={best['t_on']}, T_off={best['t_off']}, "
          f"median_filter_size={best['median_filter_size']}")
    print(f"  val F1={best['f1']*100:.2f}%, precision={best['precision']*100:.2f}%, "
          f"recall={best['recall']*100:.2f}%")
    print(f"Saved to {OUT_PATH}")


if __name__ == "__main__":
    tune()
